### ISSUE TITLE
[Test Failure] EGS generates_shortcut_not_managed

### ISSUE THREAD

**Issue by jrtberlin** [PhilipK/BoilR#54]
While updating the AUR package I noticed that the latest version introduced a failing test.
The changelog of 0.9.15 indicates that there where indeed changes to the EGS shortcuts
`Fix issue where duplicated shortcuts could be added for Epic Games.`

```
warning: unused import: `std::path::PathBuf`
 --> src/heroic/heroic_platform.rs:6:5
  |
6 | use std::path::PathBuf;
  |     ^^^^^^^^^^^^^^^^^^
  |
  = note: `#[warn(unused_imports)]` on by default

warning: `boilr` (bin "boilr" test) generated 1 warning
    Finished test [unoptimized + debuginfo] target(s) in 0.10s
     Running unittests (target/debug/deps/boilr-2ba8f4c33a2310a6)

running 12 tests
test egs::manifest_item::tests::can_parse_item ... ok
test egs::manifest_item::tests::generates_launch_string ... ok
test egs::manifest_item::tests::generates_shortcut_managed ... ok
test egs::manifest_item::tests::generates_shortcut_with_dlc ... ok
test lutris::game_list_parser::tests::reads_id ... ok
test lutris::game_list_parser::tests::can_parse_output ... ok
test lutris::game_list_parser::tests::reads_index ... ok
test lutris::game_list_parser::tests::reads_platform ... ok
test lutris::game_list_parser::tests::reads_name ... ok
test itch::butler_db_parser::tests::parse_itch_butler_db_test ... ok
test itch::butler_db_parser::tests::parse_itch_butler_db_test_other ... ok
test egs::manifest_item::tests::generates_shortcut_not_managed ... FAILED

failures:

---- egs::manifest_item::tests::generates_shortcut_not_managed stdout ----
thread 'egs::manifest_item::tests::generates_shortcut_not_managed' panicked at 'assertion failed: `(left == right)`
  left: `"C:\\Games\\MarvelGOTG/retail/gotg.exe"`,
 right: `"\"C:\\Games\\MarvelGOTG/retail/gotg.exe\""`', src/egs/manifest_item.rs:151:9
stack backtrace:
   0:     0x561eb71c61ac - std::backtrace_rs::backtrace::libunwind::trace::hc419169bf6ef9454
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x561eb71c61ac - std::backtrace_rs::backtrace::trace_unsynchronized::h9d59fe14733c6869
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x561eb71c61ac - std::sys_common::backtrace::_print_fmt::h7b4753f1990145e4
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x561eb71c61ac - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he933bf90d5f823a3
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x561eb71ebabc - core::fmt::write::h4f22e68bd4c318cf
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/fmt/mod.rs:1168:17
   5:     0x561eb71c1233 - std::io::Write::write_fmt::h592a6d7050d8d741
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/io/mod.rs:1660:15
   6:     0x561eb71c8882 - std::sys_common::backtrace::_print::h53eaa013323ce8bd
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x561eb71c8882 - std::sys_common::backtrace::print::hddd71819e54744d2
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x561eb71c8882 - std::panicking::default_hook::{{closure}}::ha7bb60f433497f90
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:211:50
   9:     0x561eb71c84d1 - std::panicking::default_hook::he08c1b6dbe4ebf2d
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:225:9
  10:     0x561eb71c8ed3 - std::panicking::rust_panic_with_hook::h4a7addec02e7dc8c
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:606:17
  11:     0x561eb71c8bf0 - std::panicking::begin_panic_handler::{{closure}}::hd61a91341efd4038
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:502:13
  12:     0x561eb71c6654 - std::sys_common::backtrace::__rust_end_short_backtrace::hf785c5cc16e3ea16
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys_common/backtrace.rs:139:18
  13:     0x561eb71c8929 - rust_begin_unwind
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:498:5
  14:     0x561eb71131e1 - core::panicking::panic_fmt::ha2f5c0f1190ddcde
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/panicking.rs:107:14
  15:     0x561eb71ea668 - core::panicking::assert_failed_inner::h7483db813f019ac1
  16:     0x561eb713084e - core::panicking::assert_failed::hc337a68081ad4721
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/panicking.rs:145:5
  17:     0x561eb7132cac - boilr::egs::manifest_item::tests::generates_shortcut_not_managed::h756c52deb5a0b8f0
                               at /home/jrt/repos/arch/steam-boilr-gui/src/BoilR-v.0.9.15/src/egs/manifest_item.rs:151:9
  18:     0x561eb7116b0a - boilr::egs::manifest_item::tests::generates_shortcut_not_managed::{{closure}}::hccec71297ebb78a0
                               at /home/jrt/repos/arch/steam-boilr-gui/src/BoilR-v.0.9.15/src/egs/manifest_item.rs:141:5
  19:     0x561eb711764e - core::ops::function::FnOnce::call_once::h7a2319120345644b
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/ops/function.rs:227:5
  20:     0x561eb715ed23 - core::ops::function::FnOnce::call_once::h53fdc358bc7dbf8c
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/ops/function.rs:227:5
  21:     0x561eb715ed23 - test::__rust_begin_short_backtrace::h6d54b178308621f8
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/test/src/lib.rs:574:5
  22:     0x561eb715da1f - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h69fe35f25d93ce2e
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/alloc/src/boxed.rs:1854:9
  23:     0x561eb715da1f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::hb6794449d6bdd6a4
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/panic/unwind_safe.rs:271:9
  24:     0x561eb715da1f - std::panicking::try::do_call::h86ecae378ef4ecea
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:406:40
  25:     0x561eb715da1f - std::panicking::try::h8a739f411eba0aeb
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:370:19
  26:     0x561eb715da1f - std::panic::catch_unwind::h51bf51d338d95b3e
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panic.rs:133:14
  27:     0x561eb715da1f - test::run_test_in_process::h62f855143a5ac361
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/test/src/lib.rs:597:18
  28:     0x561eb715da1f - test::run_test::run_test_inner::{{closure}}::hc671f96ce76fa8f7
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/test/src/lib.rs:491:39
  29:     0x561eb7166d81 - test::run_test::run_test_inner::{{closure}}::h53eb8d36bf6dafad
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/test/src/lib.rs:518:37
  30:     0x561eb7166d81 - std::sys_common::backtrace::__rust_begin_short_backtrace::h77ad2a047f7bf9c7
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys_common/backtrace.rs:123:18
  31:     0x561eb713375f - std::thread::Builder::spawn_unchecked::{{closure}}::{{closure}}::h2a3ec89bda1527ac
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/thread/mod.rs:477:17
  32:     0x561eb713375f - <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once::h60d3d0a54fd22b12
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/panic/unwind_safe.rs:271:9
  33:     0x561eb713375f - std::panicking::try::do_call::hebf146641056d110
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:406:40
  34:     0x561eb713375f - std::panicking::try::h3f99ff28acdfc3ff
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panicking.rs:370:19
  35:     0x561eb713375f - std::panic::catch_unwind::h228c651b1ce4aa64
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/panic.rs:133:14
  36:     0x561eb713375f - std::thread::Builder::spawn_unchecked::{{closure}}::ha5e99c5cc3fc7122
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/thread/mod.rs:476:30
  37:     0x561eb713375f - core::ops::function::FnOnce::call_once{{vtable.shim}}::h140fa784255088e8
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/core/src/ops/function.rs:227:5
  38:     0x561eb71cea63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h2f7659ee59dd0ada
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/alloc/src/boxed.rs:1854:9
  39:     0x561eb71cea63 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h95b83a7b24076276
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/alloc/src/boxed.rs:1854:9
  40:     0x561eb71cea63 - std::sys::unix::thread::Thread::new::thread_start::h1cd6c1faf6f6ab03
                               at /rustc/28c8a34e18fc05277c81328d1bbf5ed931f4d22e/library/std/src/sys/unix/thread.rs:108:17
  41:     0x7f455d9695c2 - start_thread
  42:     0x7f455d9ee584 - __clone
  43:                0x0 - <unknown>


failures:
    egs::manifest_item::tests::generates_shortcut_not_managed

test result: FAILED. 11 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.04s

error: test failed, to rerun pass '--bin boilr'
```

**Comment by PhilipK** [comment]
Ah, this is my fault. I found out that steam prefers not to have " quotes around paths now. But I forgot to correct the unit tests. Those tests are not critical and the tool should work as intended.

I will update the tests asap.

**Comment by PhilipK** [comment]
Alright, tests have been fixed.
